git:
  depth: 3

language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.x ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv config-add tests/php.ini
  - composer install
  - npm install
  - ./node_modules/.bin/jshint assets/js/{core,components}

script:
  - phpunit -c tests/units.sqlite.xml
  - phpunit -c tests/units.postgres.xml
  - phpunit -c tests/units.mysql.xml
  - phpunit tests/configtest
